#!/bin/bash
#
# roguepc-gnome-terminal - Gnome Terminal customization for roguepc
#
#    Copyright (C) 2015 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>
#
# Launches the game in a new Gnome Terminal window using the custom profile
#------------------------------------------------------------------------------

# default options
fullscreen=0
title='Rogue PC'
profile='RoguePC'

#------------------------------------------------------------------------------

rogueargs=()
gamecmd=
here=$(dirname "$(readlink -f "$0")")
for cmd in "$here"/src/rogue{-sdl,-ascii,}; do
	if [[ -x "$cmd" ]]; then gamecmd=$cmd; break; fi
done

usage() {
	echo "Launch Rogue PC in a new Gnome Terminal window using the custom profile"
	echo "Usage: ${0##*/} [-h|--help] [-f|--full[-]screen] [-r|--rogue CMD|PATH] [--] [rogue args...]"
	exit
}

fatal() { echo "$*" >&2; exit 1; }

while (( $# )); do
	case "$1" in
	-h|--help) usage;;
	-f|--full-screen|--fullscreen) fullscreen=1;;
	-r|--rogue      )
		(( $# >= 2 )) && [[ -n "$2" ]] || fatal "$1 requires an executable"
		shift; gamecmd=$1;;
	   --rogue=*    ) gamecmd=${1#*=}; [[ -n "$gamecmd" ]] || fatal "--rogue requires an executable";;
	--) shift; rogueargs+=( "$@" ); break;;
	-*) echo "invalid option: $1" >&2; exit 1;;
	*) rogueargs+=( "$1" );;
	esac
	shift
done
if [[ -z "$gamecmd" ]]; then
	echo "No game found, use ${0##*/} --rogue to set the executable" >&2
	exit 1
fi

if [[ "$gamecmd" != */* ]]; then
	gamecmd=$(type -P -- "$gamecmd") || fatal "Game executable not found"
fi
gamecmd=$(readlink -f -- "$gamecmd") || fatal "Could not resolve game executable"
[[ -x "$gamecmd" && ! -d "$gamecmd" ]] || fatal "Game is not executable: $gamecmd"

gtargs=(
	--profile "$profile"
	--title "$title"
	--window
	--hide-menubar
	--geometry=80x25
)

if ((fullscreen)); then
	gtargs+=(--full-screen)
fi

if [[ "${gamecmd%/*}" == "$here/src" ]]; then
	cd -- "$here/src" || exit 1
fi
exec gnome-terminal "${gtargs[@]}" --working-directory "$PWD" -- "$gamecmd" "${rogueargs[@]}"
