#!/bin/bash
#
# roguepc - Launcher for Rogue PC
#
#    Copyright (C) 2015 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>
#
# Chooses and finds rogue-sdl (for splash) or bare rogue and a suitable terminal

sdl=1
cmd=
rogueargs=()
here=$(dirname "$(readlink -f "$0")")

exists()  { type "$@" >/dev/null 2>&1; }
fatal()   { echo "$*" >&2; exit 1; }

findcmd() {
	local bin=rogue${1:+-$1}
	if [[ "$cmd" ]]; then return; fi
	if [[ -x "$here"/src/"$bin" ]]; then
		cmd=$here/src/$bin
	elif cmd=$(type -P -- "$bin"); then
		return 0
	else
		return 1
	fi
}

usage() {
	echo "Launch Rogue PC"
	echo "Usage: ${0##*/} [-h|--help]" \
		"[-f|--full[-]screen]" \
		"[-S|--no-splash]" \
		"[-r|--rogue CMD|PATH]" \
		"[--] [roguepc args]"
	exit
}

while (( $# )); do
	case "$1" in
	-h|--help) usage;;
	-S|--no-splash) sdl=0;;
	-r|--rogue)
		(( $# >= 2 )) && [[ -n "$2" ]] || fatal "$1 requires an executable"
		shift; cmd=$1;;
	--rogue=*) cmd=${1#*=}; [[ -n "$cmd" ]] || fatal "--rogue requires an executable";;
	--) shift; break;;
	*) rogueargs+=( "$1" );;
	esac
	shift
done
gameargs=("$@")


if [[ -z "$cmd" ]] && ((sdl)); then
	if findcmd "sdl"; then
		if exists ldd && ldd "$cmd" 2>/dev/null | grep -q 'not found'; then
			echo "rogue-sdl has missing shared libraries, disabling splash screen." >&2
			cmd=
		fi
	else
		echo "rogue-sdl not found, disabling splash screen." \
			"Run 'make sdl' in ./src to enable" >&2
	fi
fi


if [[ -z "$cmd" ]] && ! findcmd; then
	echo "rogue not found. Run 'make' or 'make all' in ./src and try again" >&2
	exit 1
fi

if [[ "$cmd" != */* ]]; then
	cmd=$(type -P -- "$cmd") || fatal "Game executable not found"
fi
cmd=$(readlink -f -- "$cmd") || fatal "Could not resolve game executable"
[[ -x "$cmd" && ! -d "$cmd" ]] || fatal "Game is not executable: $cmd"

if [[ "${cmd%/*}" == "$here/src" ]]; then
	cd -- "$here/src" || exit 1
fi

if   [[ "$DISPLAY" ]] && exists xterm; then
	exec "$here"/roguepc-xterm          --rogue "$cmd" "${rogueargs[@]}" -- "${gameargs[@]}"
elif [[ "$DISPLAY" ]] && exists gnome-terminal; then
	exec "$here"/roguepc-gnome-terminal --rogue "$cmd" "${rogueargs[@]}" -- "${gameargs[@]}"
else
	exec "$cmd" "${rogueargs[@]}" "${gameargs[@]}"
fi
